### ISSUE TITLE
Type Name Not Findable

### ISSUE THREAD

**Issue by gooddavvy** [asolpshinning/carbon-solid#1]
# Hi dad, I can't find a type for the chart with the name "Meter chart - with statuses" that could be `MeterChartOptions`

![githubissue1_carbon-solid_asolpshinning](https://user-images.githubusercontent.com/110428134/216408584-ed3a8b18-b3ee-44dd-8936-0ba1a94274ad.png)

Did you see that(above)? It said the import
```typescript
import { MeterChartOptions } from "@carbon/charts/interfaces";
```
was fine but look at this:

![githubissue2_carbon-solid_asolpshinning](https://user-images.githubusercontent.com/110428134/216411688-5c9127a6-e2ec-4575-80d8-28745d0e575f.png)

Please help, thanks dad!

**Comment by asolpshinning** [comment]
As in our discussion, I have explained how to get the correct type. See code below for reference:

```ts
import { ChartConfig, MeterChartOptions, Statuses } from "@carbon/charts/interfaces";
import { SolidMeterChart } from "../chartsLibrary";

const data = [
  {
    group: "Dataset 1",
    value: 56,
  },
];


const options = {
  title: "Meter Chart - with statuses",
  meter: {
    peak: 80,
    status: {
      ranges: [
        {
          range: [0, 50],
          status: "success",
        },
        {
          range: [50, 60],
          status: "warning",
        },
        {
          range: [60, 100],
          status: "danger",
        },
      ],
    },
  },
  height: "100px",
} as MeterChartOptions;

type Option = ChartConfig<MeterChartOptions>;

export default function MeterChartExample() {
  return (
    <div>
      <SolidMeterChart {...({ data, options })} />{" "}
      {/* issue posted on repo, I took a snapshot on this line and I put it in the issue */}
    </div>
  );
}

```

**Comment by gooddavvy** [comment]
Thanks for that, all you referred to in your approval will be fixed, as well.

**Comment by gooddavvy** [comment]
Wait a min, one more thing.
I did the exact same thing, and I exported it, but I keep on getting the same error.
That component is `null`
